"""initial schema (baseline)

Baselines the whole schema from the ORM metadata so existing models map 1:1 with
migration history. Subsequent changes should be proper autogenerated diffs
(`alembic revision --autogenerate -m "..."`). The pgvector extension is created by
db.base._migrate before this runs.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-29
"""
from typing import Sequence, Union

from alembic import op

from app.db.base import Base
from app.db import models  # noqa: F401  (register mappers on Base.metadata)

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
